# -*- mode: ruby -*-
# vi: set ft=ruby :

N = 2

Vagrant.configure("2") do |config|
    
    config.vm.define "w-k8s-master" do |cfg|
        
        cfg.vm.box = "whatwant/Ubuntu-20.04-Server"
        cfg.vm.box_version = "0.2.0"
        
        cfg.vm.hostname = "master"
        cfg.vm.network "public_network", ip: "192.168.100.200"
        
        cfg.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.cpus = "2"
            vb.memory = "2048"
        end
        
        cfg.vm.provision "shell", inline: <<-SHELL
            apt-get update
            apt-get upgrade -y
        SHELL
    end
    

    (1..N).each do |i|

        config.vm.define "w-k8s-worker#{i}" do |cfg|

            cfg.vm.box = "whatwant/Ubuntu-20.04-Server"
            cfg.vm.box_version = "0.2.0"
            
            cfg.vm.hostname = "worker#{i}"
            cfg.vm.network "public_network", ip: "192.168.100.20#{i}"
            
            cfg.vm.provider "virtualbox" do |vb|
                vb.gui = false
                vb.cpus = "1"
                vb.memory = "1280"
            end
            
            cfg.vm.provision "shell", inline: <<-SHELL
                apt-get update
                apt-get upgrade -y
            SHELL
        end
    end
end