apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim

spec:
  storageClassName: manual

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 500Mi

  selector:
    matchLabels:
      release: "stable"
    matchExpressions:
      - {key: env, operator: In, values: [staging]}
