apiVersion: batch/v1
kind: CronJob

metadata:
  name: cj-every-fifteen-minutes

spec:
  schedule: "0,15,30,45 * * * *"

  jobTemplate:
    spec:
      backoffLimit: 3

      template:
        metadata:
          labels:
            app: periodic-batch-job

        spec:
          containers:
          - name: pi
            image: perl:5.34.1
            command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]

          restartPolicy: Never
