apiVersion: v1
kind: PersistentVolume

metadata:
  name: pv-hostpath
  labels:
    type: local

spec:
  storageClassName: manual

  persistentVolumeReclaimPolicy: Retain

  capacity:
    storage: 100Mi

  accessModes:
    - ReadWriteOnce

  hostPath:
    path: "/tmp/pv-data"
    type: DirectoryOrCreate
