apiVersion: v1
kind: Service
metadata:
  name: svc-node-et

spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30123

  selector:
    app: node-web

  externalTrafficPolicy: Local
